playlist = 
{
	tracks = 
	{		
		"ambient_ingame_01",
		"ambient_ingame_02",
		"ambient_ingame_04",
		"battle_ingame_01",
		"mu_ig_str_chaos",
		"mu_ig_str_eldar",
		"mu_ig_str_impgd",
		"mu_ig_str_necron",
		"mu_ig_str_ork",
		"mu_ig_str_spacemarine",
		"mu_ig_str_tau",
		"mu_ig_theme_nightbringer",
		"music_acid",
		"music_chant",
		"music_coming_of_chaos",
		"music_dawnofwartheme",
		"music_eldartheme",
		"music_eldarthemev2",
		"music_evil_isador_theme",
		"music_force_commander_theme",
		"music_imperial_guard_theme",
		"music_invasion_theme",
		"music_main_title",
		"music_msd1",
		"music_msd2",
		"music_msd3",
		"music_msd4",
		"music_msd5c",
		"music_msd5o",
		"music_mso1",
		"music_mso2",
		"music_mso3",
		"music_mso4",
		"music_mso5e",
		"music_mso5i",
		"music_necron_theme",
		"music_ork_theme",
		"music_tank_march",
		"music_theme_chaos_01",
		"music_theme_spacemarines_01",
		"music_urban_wasteland",
		"music_warhammer40ktheme",
		"stinger_pressure_stinger",
		"stinger_tensedanger",
	},
	
	silence_min = 0.0,
	silence_max = 0.0,
	
	order = false,
}
